### PR TITLE
Slot:  add Semigroup instance (GHC 8.4 compat)

### LINKED ISSUE #45: Build error with GHC 8.4.1-alpha1
GHC 8.4.1-alpha1 was [announced](https://mail.haskell.org/pipermail/ghc-devs/2017-December/015235.html). While testing [Agda](https://github.com/agda/agda) with this version of GHC, I got the following error on hashtables (master branch):

```
$ cabal install
...
src/Data/HashTable/ST/Basic.hs:491:10: error:
    • No instance for (Semigroup Slot)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid Slot’
    |
491 | instance Monoid Slot where
    |          ^^^^^^^^^^^
Failed to install hashtables-1.2.2.1
```

Blocking https://github.com/agda/agda/issues/2878.

### PR DESCRIPTION
**Pull request by deepfire**
Fixes #45. Tested with GHC 8.4.1-alpha1, 8.0.2.

### CODE REVIEW

**Comment by deepfire** [comment]
cc @gregorycollins

**Comment by asr** [comment]
GHC 8.4.1-alpha3 was [announced](https://mail.haskell.org/pipermail/ghc-devs/2018-February/015354.html). Could someone merge this PR please?

**Comment by asr** [comment]
Could someone merge this PR, please (the missing support for GHC 8.4.1 is blocking agda/agda#2878).

**Comment by ndmitchell** [comment]
Also blocking the `debug` library - merging would be great.

**Comment by mgmeier** [comment]
@gregorycollins also blocking `hasql`.

Sorry to be so blunt, but merge this PR already, or give up maintaining this package!
You should at least appreciate other ppl fixing stuff for you and respond to it. And this issue is one you should've seen coming for a long time now, e.g. when building your package with `-Wcompat`.

**Comment by cocreature** [comment]
@mgmeier I strongly disagree with your tone here. Most people do open source in your free time and telling them to give up doing so in their limited is rude, stops them from wanting to do more open source and isn’t helpful to anyone. You could have expressed your same sentiment by suggesting that Gregory takes on a comaintainer or even offer to be one yourself which is a significantly more friendly and constructive approach.

Anyway, this is not the right place for a discussion on good manners in open source, so let’s please leave it at that.

**Comment by mgmeier** [comment]
Ok I see. @cocreature I do not need lecturing or behaviour policing from you, at all.

Apart from that, I consider preparing a PR for Gregory very helpful - I would have prepared one myself if there hadn't been any.

Not responding to the help other people offer, over the course of months - that is rude, IMHO. Given that merging and releasing would take few minutes, spare time limitations are a non-argument here.

However, I want to apologize to anyone who felt offended - that was not my intention.

**Comment by gregorycollins** [comment]
I merged the other one. I don't have very much time to maintain these libraries right now, sorry.

**Pull request closed without merging**
