### PR TITLE
fix 0.7 primitive support, add travis CI and kill some warnings

### PR DESCRIPTION
**Pull request by cartazio**
https://travis-ci.org/cartazio/hashtables/builds/539491966 is the build matrix i setup

### CODE REVIEW

**Comment by cartazio** [comment]
@hvr @vmchale @gregorycollins this should fix everything up super nice :) 
(the previous fix wasn't complete / fully tested so those releases on hackage had <.7 added by trustees)

**Comment by cartazio** [comment]
the CI should be a tad more informative now https://travis-ci.org/cartazio/hashtables/builds/539494439

**Comment by cartazio** [comment]
@ryangiscott @hvr why am i seeing a build failure on the 8.8.1 leg of the build matrix around base constraints?

**Comment by cartazio** [comment]
https://travis-ci.org/cartazio/hashtables/builds/539497933 
NB: you can easily enable travis CI on the project now that you have a .travis.yml :)

**Comment by cartazio** [comment]
NB: i used haskell-ci-0.3.20190521 from master repo  https://github.com/haskell-CI/haskell-ci to generate the .travis.yml, there may be things that need updates there some point

**Comment by RyanGlScott** [comment]
From a quick glance, my guess is that this `haskell-ci`–generated `.travis.yml` is not correctly handling GHC 8.8. Or rather, I don't think it's accurate to call it "`haskell-ci`–generated", since it looks like this `.travis.yml` file was edited by hand? For instance, there is a `GHCHEAD` environment variable, but the `.travis.yml` file is missing [these important lines](https://github.com/haskell-CI/haskell-ci/blob/a517459b7a82ae70e0d08399a60871c3f0ec2d1d/.travis.yml#L103-L114), which actually does something when `GHCHEAD` is defined.

This is why I consider editing `.travis.yml` files by hand to be an absolute faux pas: it's easy to overlook something, and just as easy to screw something up. My recommendation is to tweak your `haskell-ci` configuration so that it actually generates all of this stuff for you. At the minimum, I think you'll need to do the following:

* Add `GHC==8.8.1` to `tested-with` in the `.cabal` file so that `haskell-ci` picks up on the fact that it should be generating a configuration for 8.8.1.
* If you want to test GHC HEAD as well, you need to use `haskell-ci`'s `--ghc-head` flag. You can accomplish it by either including that in the `REGENDATA` at the bottom of the `.travis.yml` file (as in [this example](https://github.com/haskell-CI/haskell-ci/blob/66dd79b17e55e6dee94664888a7c0da8698582c3/fixtures/cabal.project.empty-line.travis.yml#L211)), or by listing it in a separate `cabal.haskell-ci` file (see [here](https://github.com/haskell-CI/haskell-ci/blob/a517459b7a82ae70e0d08399a60871c3f0ec2d1d/cabal.haskell-ci#L7) and [here](https://github.com/haskell-CI/haskell-ci/blob/a517459b7a82ae70e0d08399a60871c3f0ec2d1d/.travis.yml#L200) for how to do this).

Hope this helps!

**Comment by cartazio** [comment]
thx, i'm still learning that new setup ! :) 

should be fixed now https://travis-ci.org/cartazio/hashtables/builds/539767457

**Comment by cartazio** [comment]
@gregorycollins  bump :)

**Comment by cartazio** [comment]
@RyanGlScott i kinda just copied the ones over from primitive ... does that look ok>?

**Comment by cartazio** [comment]
(all green build wise)

**Comment by RyanGlScott** [comment]
Cool!

A lot of those `cabal.haskell-ci` settings are only necessary for `primitive`'s unusual configuration. In particular, I think you could get away without having `jobs`, `install-dependencies`, or `installed`.

**Comment by cartazio** [comment]
more green! https://travis-ci.org/cartazio/hashtables/builds/539823000

**Comment by cartazio** [comment]
@glguy @gregorycollins @hvr Hey Greg: can we get this out or would you authorize an NMU by hackage admins? :)

**Comment by cartazio** [comment]
hrm, @mgmeier seems to have upload perms, maybe he can help?

**Pull request merged**
