### PR TITLE
Bump vector depedency to <0.14 and support GHC 9.4.2

### PR DESCRIPTION
**Pull request by marshall-lee**
- Bump vector depedency to <0.14
- Bump GHC 9.2 version to 9.2.4
- Enable build for GHC 9.4.2

### CODE REVIEW

**Comment by erikd** [comment]
Thanks!

**Comment by marshall-lee** [comment]
@erikd thank you! when do you plan to release?

**Comment by erikd** [comment]
Really busy right now. Will do a release this weekend.

**Comment by erikd** [comment]
@marshall-lee Version `1.3.1` is now on Hackage.

**Pull request merged**
